apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "${PARAM_STORE_SECRET_STORE_NAME}" 
  namespace: "${NAMESPACE}"
spec:
  provider:
    aws:
      service: ParameterStore
      region: "${AWS_REGION}"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: "${AWS_SECRET_NAME}"
            key: "aws-access-key"
          secretAccessKeySecretRef:
            name: "${AWS_SECRET_NAME}"
            key: "aws-secret-key"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${PARAM_STORE_SECRET_NAME}"
  namespace: "${NAMESPACE}"
spec:
  refreshInterval: "${REFRESH_INTERVAL}"
  secretStoreRef:
    name: "${PARAM_STORE_SECRET_STORE_NAME}"
    kind: "SecretStore"
  target:
    name: "${PARAM_STORE_SECRET_NAME}"
  data:
    - secretKey: "DB_PASSWORD"
      remoteRef:
        key: "/${NAME_PREFIX}/database/password"
    - secretKey: "DB_USERNAME"
      remoteRef:
        key: "/${NAME_PREFIX}/database/username"