#  ArgoCD ApplicationSet that deploys applications from a Git repository.
# It uses the Git generator to create applications based on the directory structure in the repository.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-dev-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'git@github.com/deelaa-marketplace/ecommerce-k8s-gitops.git'
        revision: HEAD
        directories:
          - path: 'clusters/dev/apps/*'
            values:
              env: 'dev'
              namespace: 'ecommerce-dev'
          - path: 'clusters/argocd/*'
            exclude: true

  template:
    metadata:
      name: '{{.path.basename}}-{{.values.env}}'
      namespace: '{{.values.namespace}}'
      labels:
        app: '{{.path.basename}}'
        env: '{{.values.env}}'
        app.kubernetes.io/instance: '{{.path.basename}}'
        app.kubernetes.io/part-of: '{{.values.namespace}}'

    spec:
      project: ecommerce-app
      source:
        repoURL: 'git@github.com/deelaa-marketplace/ecommerce-k8s-gitops.git'
        targetRevision: 'HEAD'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
