apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "cart-service-dev-param-store-external-secret"
  namespace: "ecommerce-dev"
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: "dev-parameter-store-secret-store"
    kind: "SecretStore"
  target:
    name: "cart-service-dev-parameter-store-secret"
  data:
    - secretKey: "DB_PASSWORD"
      remoteRef:
        key: "/test/database/cart-service/password"
    - secretKey: "DB_USERNAME"
      remoteRef:
        key: "/test/database/cart-service/username"