apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: "dev-ecr-token-external-secret"
  namespace: "ecommerce-dev"
spec:
  region: "${AWS_REGION}"
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: "dev-aws-credentials"
        key: "aws-access-key"
      secretAccessKeySecretRef:
        name: "dev-aws-credentials"
        key: "aws-secret-key"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "dev-ecr-external-secret"
  namespace: "ecommerce-dev"
spec:
  refreshInterval: "12h"
  target:
    name: "dev-ecr-secret"
    template:
      engineVersion: v2
      mergePolicy: "Merge"
      metadata:
        labels:
          app: "ecommerce-dev"
          env: "dev"
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint }}": {
                "auth": '{{ .username ":" .password | join "" | b64enc }}'
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: "generators.external-secrets.io/v1alpha1"
          kind: "ECRAuthorizationToken"
          name: "dev-ecr-token-external-secret"