apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ecommerce

commonLabels:
  app: cart-service
  env: default

commonAnnotations:
  app.interpolate: "true"

images:
- name: cart-service
  newName: 886129832542.dkr.ecr.eu-west-1.amazonaws.com/cart-service
  newTag: latest

configMapGenerator:
  - name: app-config
    behavior: merge  # Ensures values are merged instead of conflicting
    literals:
      - APP_NAME=cart-servicex
      - APP_PORT=80
      - APP_NAMESPACE=ecommerce
      - ENV=default
      - LOG_LEVEL=debug

transformers:
  - ../../base/replacement.yaml
