apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce-app
  namespace: argocd
spec:
  sourceRepos:
    - "git@github.com/deelaa-marketplace/ecommerce-k8s-gitops.git"
    - "https://github.com/deelaa-marketplace/ecommerce-k8s-gitops.git"
  destinations:
    - namespace: "ecommerce-dev"
      server: "https://kubernetes.default.svc"
#    - namespace: "ecommerce-prod"
#      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

