apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-app-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  #project: "ecommerce-app"
  name: "ecommerce-app-repo"
  type: "git"
  url: "git@github.com:deelaa-marketplace/ecommerce-k8s-gitops.git"
data:
  sshPrivateKey: |
    ${SSH_PRIVATE_KEY_B64}
