apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifest.yaml

namespace: ecommerce-dev

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: ecm-config-server
      env: dev

commonAnnotations:
  app.interpolated.resource: "true"
  kustomize.interpolated.resource: "true"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ecm-config-server
    newName: 886129832542.dkr.ecr.eu-west-1.amazonaws.com/ecm-config-server
    newTag: v1.0.0

configMapGenerator:
  - name: app-config
    #behavior: merge  # ✅ Ensures values are merged instead of conflicting
    literals:
      - APP_NAME=ecm-config-server
      - APP_NAMESPACE=ecommerce-dev
      - ENV=dev
      - APP_ENV=test
      - APP_PORT=80
  - name: ecm-config-server
    #behavior: merge  # Ensures values are merged instead of conflicting
    literals:
      - ENV=test
      - DB_NAME=ecm-config-server
      - DB_HOST=test.c8flhmnxenjx.eu-west-1.rds.amazonaws.com
      - DB_PORT=5432

    options:
      disableNameSuffixHash: true

#transformers:
#  - ../../../../apps/base/replacement.yaml