apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "parameter-store-secret-store"
  namespace: "ecommerce-dev"
spec:
  provider:
    aws:
      service: ParameterStore
      region: "${AWS_REGION}"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: "dev-aws-credentials"
            key: "aws-access-key"
          secretAccessKeySecretRef:
            name: "dev-aws-credentials"
            key: "aws-secret-key"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "parameter-store-external-secret"
  namespace: "ecommerce-dev"
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: "parameter-store-secret-store"
    kind: "SecretStore"
  target:
    name: "parameter-store-secret"
  data:
    - secretKey: "DB_PASSWORD"
      remoteRef:
        key: "/default/database/password"
    - secretKey: "DB_USERNAME"
      remoteRef:
        key: "/default/database/username"
    - secretKey: "CONFIG_SERVER_USERNAME"
      remoteRef:
        key: "/default/config-server/username"
    - secretKey: "CONFIG_SERVER_PASSWORD"
      remoteRef:
        key: "/default/config-server/password"
    - secretKey: "CONFIG_SERVER_URI"
      remoteRef:
        key: "/default/config-server/uri"
