apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/example/repo.git"
  destinations:
    - namespace: "dev"
      server: "https://kubernetes.default.svc"
    - namespace: "prod"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
