apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$APP_NAME"
  #namespace: ecommerce-dev
  #labels:
    #app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "$APP_NAME"
  template:
    metadata:
      labels:
        app: "$APP_NAME"
        env: "$ENV"
    spec:
      containers:
        - name: $APP_NAME
          image: nginx:latest
          ports:
            - containerPort: $APP_PORT
          # The containerPort is set to the value of APP_PORT from the ConfigMap
          # This allows the container to listen on the specified port
          envFrom:
            - configMapRef:
                name: "$APP_NAME-config"
            - secretRef:
                name: "$APP_NAME-secret"
          resources:
            requests:
              cpu: "500m" # Requests 500 millicores (~0.5 vCPU)
              memory: "512Mi" # Requests 512 MiB of RAM
            limits:
              cpu: "1" # Limits to 1 vCPU
              memory: "1Gi" # Limits to 1 GiB of RAM
      imagePullSecrets:
        - name: ecr-secret
