apiVersion: v1
kind: Secret
metadata:
  name: "$APP_NAME"
 # namespace: default
type: Opaque
stringData:
  DB_PASSWORD: "arn:aws:ssm:eu-west-1:886129832542:parameter/test/database/cart-service/password"
  DB_USERNAME: "arn:aws:ssm:eu-west-1:886129832542:parameter/test/database/cart-service/username"
  CONFIG_SERVER_USERNAME: "arn:aws:ssm:eu-west-1:886129832542:parameter/default/config-server/username"
  CONFIG_SERVER_PASSWORD: "arn:aws:ssm:eu-west-1:886129832542:parameter/default/config-server/password"
  CONFIG_SERVER_URI: "arn:aws:ssm:eu-west-1:886129832542:parameter/default/config-server/uri"
