apiVersion: v1
kind: Secret
metadata:
  name: "$APP_NAME"
 # namespace: default
type: Opaque
data:
  DB_NAME: "cart-service"
  DB_HOST: "test.c8flhmnxenjx.eu-west-1.rds.amazonaws.com"
  DB_PORT: "5432"
  ENV: "$ENV"
  AWS_ACCESS_KEY: "${AWS_ACCESS_KEY_B64}"
  AWS_SECRET_KEY: "${AWS_SECRET_KEY_B64}"
  AWS_REGION: "${AWS_REGION_B64}"

