apiVersion: v1
kind: Service
metadata:
  name: "$APP_NAME"
 #  namespace: default
 # labels:
 #    app: cart-service
spec:
  selector:
    app: "$APP_NAME"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP