apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - config-map.yaml
  - secret.yaml

namespace: ecommerce-dev

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: application
      env: dev

commonAnnotations:
  app.interpolated.resource: "true"
  app.kubernetes.io/managed-by: kustomize
  kustomize.interpolated.resource: "true"


images:
  - name: cart-service
    newName: 886129832542.dkr.ecr.eu-west-1.amazonaws.com/cart-service
    newTag: latest


configMapGenerator:
  - name: app-config
    literals:
      - APP_NAME=application
      - APP_CONFIG_NAME=application-config
      - APP_SERVICE_NAME=application-service
      - APP_SECRET_NAME=application-secret
      - APP_PORT=80
      - ENV=dev
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.interpolated.resource: "false"
        kustomize.generated.resource: "true"