apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: "${NAME_PREFIX}-ecr-token-generator"
  namespace: "${NAMESPACE}"
spec:
  region: "${AWS_REGION}"
  auth:
    secretRef:
      accessKeyIDSecretRef:
        name: "${AWS_SECRET_NAME}"
        key: "aws-access-key"
      secretAccessKeySecretRef:
        name: "${AWS_SECRET_NAME}"
        key: "aws-secret-key"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${NAME_PREFIX}-ecr-external-secret"
  namespace: "${NAMESPACE}"
spec:
  refreshInterval: "${REFRESH_INTERVAL:-6h}"
  target:
    name: "${NAME_PREFIX}-ecr-secret"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: "generators.external-secrets.io/v1alpha1"
          kind: "ECRAuthorizationToken"
          name: "${NAME_PREFIX}-ecr-token-generator"